import './styles.css';
import { request } from './api.js';
import { filterRows, readPreference, validateValue, writePreference } from './model.js';
import { queueValue, readQueue, removeQueuedValue, writeQueue } from './sync-queue.js';
import { readStoreCache, writeStoreCache } from './store-cache.js';
import { allPhotos, getPhoto, removePhoto, savePhoto } from './photo-queue.js';

const config = window.APP_CONFIG || {};
const app = document.querySelector('#app');
const state = { rows: [], outQueue: readQueue(localStorage), photoQueue: {}, filters: { district: readPreference(localStorage, 'sme.selectedDistrict'), account: '', status: '', query: '' } };
app.innerHTML = `<main class="shell"><header><div><p class="eyebrow">SME FIELD SALES</p><h1>บันทึกงานหน้าร้าน</h1><p class="sub">เลือกของหมด หรือเก็บรูปไว้ในเครื่อง แล้วกด Sync เพื่อส่งลงชีต</p></div><div class="header-actions"><span id="syncCount" class="sync-count">รอ Sync 0 รายการ</span><button id="sync" class="button primary" type="button">Sync ข้อมูล</button><button id="refresh" class="button secondary" type="button">↻ โหลดข้อมูลใหม่</button></div></header><section class="filters" aria-label="ตัวกรองร้านค้า"><label><span>เขต</span><select id="district"><option value="">ทุกเขต</option></select></label><label><span>Account</span><select id="account"><option value="">ทุก Account</option></select></label><label><span>สถานะ</span><select id="status"><option value="">ทั้งหมด</option><option value="pending">ยังไม่กรอก</option><option value="done">กรอกแล้ว</option></select></label><label class="search"><span>ค้นหาร้าน / รหัสสาขา</span><input id="query" type="search" placeholder="พิมพ์ชื่อร้านหรือรหัสสาขา" autocomplete="off"></label></section><section class="summary"><strong id="count">0 รายการ</strong><span id="notice" role="status">กำลังเตรียมข้อมูล…</span></section><section id="results" class="cards" aria-live="polite"></section><dialog id="entryDialog"><form method="dialog" id="entryForm"><button id="closeDialog" class="close" type="button" aria-label="ปิด">×</button><p class="eyebrow">คีย์งาน</p><h2 id="entryTitle"></h2><dl id="entryDetails"></dl><label><span>รายการ</span><select id="value" required><option value="" disabled>เลือกรายการ</option><option value="ของหมด">ของหมด</option><option value="photo">อัปโหลดรูป</option></select></label><label id="photoLabel" hidden><span>เลือกรูปภาพ</span><input id="photo" type="file" accept="image/*" capture="environment"></label><img id="preview" class="preview" alt="ตัวอย่างรูป" hidden><p id="formError" class="error" hidden></p><div class="actions"><button id="cancelEntry" type="button" class="button secondary">ยกเลิก</button><button id="save" class="button primary">บันทึก</button></div></form></dialog><footer>รูปที่ Sync สำเร็จจะแสดงในคอลัมน์ “ซื้อออกแล้ว” ของ Google Sheet</footer></main>`;
const $ = s => document.querySelector(s); const dialog = $('#entryDialog'); let activeRow;
const pendingCount = () => Object.keys(state.outQueue).length + Object.keys(state.photoQueue).length;
const escapeHtml = value => String(value).replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c]));
function unique(key, rows = state.rows) { return [...new Set(rows.map(r => r[key]).filter(Boolean))].sort((a,b) => a.localeCompare(b, 'th')); }
function optionize(select, values, first) { const keep = select.value; select.innerHTML = `<option value="">${first}</option>${values.map(v => `<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('')}`; select.value = values.includes(keep) ? keep : ''; }
function setupFilters() { const districts=unique('district'), accounts=unique('account'); if(!districts.includes(state.filters.district)) state.filters.district=''; if(!accounts.includes(state.filters.account)) state.filters.account=''; optionize($('#district'),districts,'ทุกเขต'); $('#district').value=state.filters.district; optionize($('#account'),accounts,'ทุก Account'); $('#account').value=state.filters.account; $('#status').value=state.filters.status; $('#query').value=state.filters.query; render(); }
function displayState(row) { if (state.photoQueue[row.identity]) return ['waiting','รอ Sync รูปภาพ']; if (row.pendingSync) return ['waiting','รอ Sync: ของหมด']; if (row.hasPhoto) return ['complete','อัปโหลดรูปแล้ว']; if (row.value === 'ของหมด') return ['complete','ของหมด']; return ['pending','ยังไม่กรอก']; }
function render() { const rows=filterRows(state.rows,state.filters), queued=pendingCount(); $('#count').textContent=`${rows.length} รายการ`; $('#syncCount').textContent=`รอ Sync ${queued} รายการ`; $('#sync').disabled=!queued; $('#results').innerHTML=rows.length?rows.map(r=>{const [klass,label]=displayState(r);return `<article class="card"><div class="tag">${escapeHtml(r.district)} · ${escapeHtml(r.account)}</div><h2>${escapeHtml(r.name)}</h2><p class="branch">สาขา ${escapeHtml(r.branch)}</p><p class="sku">${escapeHtml(r.sku||'—')}</p><div class="card-footer"><span class="${klass}">${label}</span><button class="button primary entry" data-id="${escapeHtml(r.identity)}" type="button">${r.hasPhoto?'แก้ไข':'คีย์งาน'}</button></div></article>`}).join(''):'<div class="empty">ไม่พบร้านที่ตรงกับเงื่อนไข</div>'; document.querySelectorAll('.entry').forEach(b=>b.addEventListener('click',()=>openEntry(b.dataset.id))); }
async function openEntry(id) { activeRow=state.rows.find(r=>r.identity===id); if(!activeRow)return; $('#entryTitle').textContent=activeRow.name; $('#entryDetails').innerHTML=`<div><dt>เขต</dt><dd>${escapeHtml(activeRow.district)}</dd></div><div><dt>Account</dt><dd>${escapeHtml(activeRow.account)}</dd></div><div><dt>รหัสสาขา</dt><dd>${escapeHtml(activeRow.branch)}</dd></div>`; $('#value').value=activeRow.value==='ของหมด'?'ของหมด':''; $('#photo').value=''; $('#photoLabel').hidden=true; $('#preview').hidden=true; const queued=await getPhoto(id); if(queued) showPreview(queued.dataUrl); $('#formError').hidden=true; dialog.showModal(); }
function applyRows(rows) { state.rows=rows.map(row=>state.outQueue[row.identity]?{...row,value:'ของหมด',pendingSync:true}:row); }
function timeLabel(value) { return new Date(value).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}); }
function loadCachedRows() { const cached=readStoreCache(localStorage); if(!cached)return; applyRows(cached.rows); $('#notice').textContent=`แสดงข้อมูลในเครื่อง ${cached.rows.length} รายการ (บันทึก ${timeLabel(cached.updatedAt)}) กำลังตรวจข้อมูลใหม่…`; setupFilters(); }
async function load() { $('#notice').textContent=state.rows.length?'กำลังตรวจข้อมูลใหม่…':'กำลังโหลดข้อมูล…'; try { const data=await request(config.apiUrl,'','list'); if(!Array.isArray(data.rows))throw new Error('API ส่งข้อมูลรายการร้านไม่ถูกต้อง'); applyRows(data.rows); writeStoreCache(localStorage,data.rows); $('#notice').textContent=`อัปเดตล่าสุด ${timeLabel(Date.now())} · เก็บ ${data.rows.length} รายการไว้ในเครื่องแล้ว`; } catch(error) { $('#notice').textContent=state.rows.length?`ใช้ข้อมูลในเครื่องชั่วคราว · ตรวจข้อมูลใหม่ไม่สำเร็จ: ${error.message}`:`โหลดข้อมูลไม่สำเร็จ: ${error.message}`; } setupFilters(); }
async function compressedDataUrl(file) { if(!file?.type.startsWith('image/'))throw new Error('กรุณาเลือกไฟล์รูปภาพ'); const source=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)}); const image=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=source}); const scale=Math.min(1,1440/Math.max(image.width,image.height)); const canvas=document.createElement('canvas'); canvas.width=Math.round(image.width*scale); canvas.height=Math.round(image.height*scale); canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height); return canvas.toDataURL('image/jpeg',.8); }
function showPreview(source){$('#preview').src=source;$('#preview').hidden=false;}
$('#closeDialog').addEventListener('click',()=>dialog.close()); $('#cancelEntry').addEventListener('click',()=>dialog.close());
$('#district').addEventListener('change',e=>{state.filters.district=e.target.value;writePreference(localStorage,'sme.selectedDistrict',e.target.value);render()}); $('#account').addEventListener('change',e=>{state.filters.account=e.target.value;render()}); $('#status').addEventListener('change',e=>{state.filters.status=e.target.value;render()}); $('#query').addEventListener('input',e=>{state.filters.query=e.target.value;render()}); $('#refresh').addEventListener('click',load);
$('#value').addEventListener('change',e=>{const photo=e.target.value==='photo';$('#photoLabel').hidden=!photo;if(!photo)$('#preview').hidden=true;}); $('#photo').addEventListener('change',async e=>{try{if(e.target.files[0])showPreview(await compressedDataUrl(e.target.files[0]));}catch(err){$('#formError').textContent=err.message;$('#formError').hidden=false;}});
$('#entryForm').addEventListener('submit',async event=>{event.preventDefault();const error=$('#formError');try{const value=$('#value').value;if(value==='photo'){const dataUrl=await compressedDataUrl($('#photo').files[0]);if(dataUrl.length>3500000)throw new Error('รูปมีขนาดใหญ่เกินไป กรุณาเลือกภาพที่เล็กลง');await savePhoto({identity:activeRow.identity,dataUrl,name:`${activeRow.branch}-${Date.now()}.jpg`,type:'image/jpeg'});state.photoQueue[activeRow.identity]=true;delete state.outQueue[activeRow.identity];writeQueue(localStorage,state.outQueue);activeRow.pendingSync=true;}else{validateValue(value);state.outQueue=queueValue(state.outQueue,activeRow.identity,value);writeQueue(localStorage,state.outQueue);activeRow.value=value;activeRow.pendingSync=true;}dialog.close();$('#notice').textContent='บันทึกในเครื่องแล้ว กรุณากด Sync เพื่อส่งลงชีต';render();}catch(err){error.textContent=err.message||'บันทึกในเครื่องไม่สำเร็จ';error.hidden=false;}});
$('#sync').addEventListener('click',async()=>{const button=$('#sync');button.disabled=true;button.textContent='กำลัง Sync…';let sent=0;const errors=[];for(const [id,value] of Object.entries(state.outQueue)){try{await request(config.apiUrl,'','save',{identity:id,value});state.outQueue=removeQueuedValue(state.outQueue,id);const row=state.rows.find(r=>r.identity===id);if(row)row.pendingSync=false;sent++;}catch(error){errors.push(error.message);}}writeQueue(localStorage,state.outQueue);for(const id of Object.keys(state.photoQueue)){try{const image=await getPhoto(id);if(!image){delete state.photoQueue[id];continue;}await request(config.apiUrl,'','upload',{identity:id,image});await removePhoto(id);delete state.photoQueue[id];const row=state.rows.find(r=>r.identity===id);if(row){row.pendingSync=false;row.hasPhoto=true;row.value='';}sent++;}catch(error){errors.push(error.message);}}const left=pendingCount();$('#notice').textContent=left?`ส่งสำเร็จ ${sent} รายการ, คงค้าง ${left} รายการ · ${errors[0]||'กรุณาลอง Sync ใหม่'}`:`Sync สำเร็จ ${sent} รายการ`;button.textContent='Sync ข้อมูล';render();});
async function initialise(){try{state.photoQueue=Object.fromEntries((await allPhotos()).map(photo=>[photo.identity,true]));}catch{$('#notice').textContent='เบราว์เซอร์นี้ไม่รองรับการเก็บรูปไว้รอ Sync';}loadCachedRows();load();} initialise();
